name: Spec Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run spec tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  spec-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        preset: [mainnet, minimal]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-spectests-${{ hashFiles('spectests/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-spectests-
          
    - name: Cache consensus spec tests
      uses: actions/cache@v3
      with:
        path: spectests/consensus-spec-tests
        key: consensus-spec-tests-${{ matrix.preset }}-${{ github.run_number }}
        restore-keys: |
          consensus-spec-tests-${{ matrix.preset }}-
          
    - name: Setup consensus spec test data
      run: |
        cd spectests
        ./setup_test_data.sh setup ${{ matrix.preset }}
        echo "CONSENSUS_SPEC_TESTS_DIR=$(./setup_test_data.sh export ${{ matrix.preset }})" >> $GITHUB_ENV
        
    - name: Download dependencies
      run: |
        cd spectests
        go mod download
        
    - name: Run spec tests
      run: |
        cd spectests
        go test -v -timeout=30m -run="TestSpec.*${{ matrix.preset }}" ./...
      env:
        CONSENSUS_SPEC_TESTS_DIR: ${{ env.CONSENSUS_SPEC_TESTS_DIR }}
